rancher/webhook-service

drivers/scale_service.go
service/handlers.go
service/webhooks_test.go

https://github.com/rancher/rancher/issues/7023

Better error code

---

drivers/scale_service.go

https://github.com/rancher/rancher/issues/7212

Check service type

---

service/construct_handler.go
service/handlers.go
service/webhooks_test.go

https://github.com/rancher/rancher/issues/7213

Check webhook names unique

---

service/construct_handler.go
service/handlers.go

https://github.com/rancher/rancher/issues/7236

Ignore register type genericObjects in ListWebhooks

---

drivers/framework.go
drivers/scale_service.go
model/driver_model.go
service/routes.go
service/webhooks_test.go

Add min max fields for scaleService driver

---

drivers/scale_service.go
model/driver_model.go
service/webhooks_test.go

https://github.com/rancher/rancher/issues/7434
Checked all endpoints and added test

Change type of amount, min max to int64

---

drivers/scale_service.go
model/driver_model.go
service/webhooks_test.go

https://github.com/rancher/rancher/issues/7445
Is adding a field `type` to all drivers okay for this -> https://github.com/rancher/rancher/issues/7445#issuecomment-273287097 @cjellick ?

Assign field 'type' to driverConfig

---

drivers/scale_service.go

https://github.com/rancher/rancher/issues/7629
@cjellick

Webhooks not allowed for global service

---

drivers/scale_service.go

https://github.com/rancher/rancher/issues/7636
@cjellick can you review this?

Webhook creation not allowed for rancher/none image

---

drivers/scale_host.go
model/driver_model.go

https://github.com/rancher/rancher/issues/7891
https://github.com/rancher/rancher/issues/7917
@cjellick can you review this?

Delete option and logs

---

drivers/scale_host.go

https://github.com/rancher/rancher/issues/7918
The code checked checked while scaling up if only custom hosts were available for cloning and returned error. But while scaling down there was no check/error needed. This PR separates the logic for "up" and "down" immediately after getting all hosts to avoid considering "custom" hosts separate while scaling down

Remove custom hosts without 500 error

---

drivers/service_upgrade.go
service/upgrade_service_test.go

https://github.com/rancher/rancher/issues/7931

Check tags

---

drivers/scale_host.go

https://github.com/rancher/rancher/issues/7963

Case insenstitive labels for hosts

---

service/routes.go

https://github.com/rancher/rancher/issues/7961

Add application/json header for errors

---

drivers/scale_host.go

https://github.com/rancher/rancher/issues/7953
The `apiClient` is used for every api call except for 
1. Getting base host to be used for cloning
2. Creating host while scaling up
The apiClient has access to accessKey and secretKey while it is created, but the raw http call for getting/creating hosts doesn't. This pr passes the keys to the raw calls.
@cjellick can you review?

Add host auth enabled

---

drivers/service_upgrade.go

https://github.com/rancher/rancher/issues/7932

Upgrade sidekicks

---

drivers/scale_host.go

https://github.com/rancher/rancher/issues/7926
https://github.com/rancher/rancher/issues/7983
There is a function for leftpadding hostnames with 0s, in case my first host is host001, so next clones would be host002, host003 and so on.
```
func leftPad(str, pad string, length int) string {
for {
if len(str) == length {
return str[0:length]
}
str = pad + str
}
}
```
before calling this, the suffix for clone was being calculated by incrementing highest suffix so far by one. This new suffix was passed as `str`,  length of the currently present clone's suffix was passed as `length` and `pad` was just `0`.
So if my current host from scaling group with highest suffix is dev9, the current suffix would be `9`. So then `str` would be `strings.Itoa(9+1)`=`10`, and `length` would be …

Left pad let to infinite for loop

---

drivers/service_upgrade.go

https://github.com/rancher/rancher/issues/7932
Only primary services/sidekicks with labels were getting upgraded with new image, but the api call to upgrade included LaunchConfig & SecondaryLaunchConfigs always. That's why upgrade was being called on the service too when only sidekick was getting upgraded to the new image as expected. This PR adds LaunchConfig in InServiceUpgradeStrategy only if primary service has the label.

Exclude not needed configs

---

drivers/scale_host.go
drivers/service_upgrade.go

https://github.com/rancher/rancher/issues/7963
https://github.com/rancher/rancher/issues/7975

Make labels case insensitive

---

Dockerfile.dapper
service/upgrade_service_test.go
trash.conf
vendor/github.com/rancher/go-rancher/api/json_writer.go

https://github.com/rancher/go-rancher/pull/142

Unicode escape

---

drivers/service_upgrade.go

When the number of service is larger then 100, upgrade service can not upgrade all of the services. We need to pass the parameter limit=-1 to get all services back.
https://github.com/rancher/rancher/issues/10258

Fix the issue that upgrade service can not upgrade all services
